spring:
  profiles:
    default: local

  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: user
    password: 1234

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

springdoc:
  api-docs:
    path: /docs
    groups:
      enabled: true

  swagger-ui:
    path: /swagger-ui
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true

  override-with-generic-response: false
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
